Save selected_hosts as permanent config file, reload configs from contents menu.

diff --git a/sshto b/sshto
--- a/sshto
+++ b/sshto
@@ -1,8 +1,8 @@
 #!/bin/bash
 #--------------------------{ Default values }---------------------------------------------------------------------------
      OPT=$1     # Options.
-     KEY=~/.ssh/id_rsa.pub # SSH key to use in command Sshkey(Add my ssh key to host).
-CONFILES=$(shopt -s nullglob; echo ~/.ssh/{config,config*[!~]})   # SSH confiles list.
+  sshdir=~/.ssh # Ssh configfiles folder
+     KEY="$sshdir/id_rsa.pub" # SSH key to use in command Sshkey(Add my ssh key to host).
   REMOTE=8080   # Remote port for tunneling.
    LOCAL=18080  # Local  port for tunneling.
    GUEST=$USER  # Alternative username to login with.
@@ -13,7 +13,7 @@ CONFILES=$(shopt -s nullglob; echo ~/.ssh/{config,config*[!~]})   # SSH confiles
     home=$PWD   # Destination folder on local  server to download\upload files and sshfs mount.
 sshfsopt=       # Sshfs options if needed
 group_id=dummy  # Group separator identification template, 'dummy' by default, don't ask why, historically)
-knwhosts=~/.ssh/known_hosts    # Path to known_hosts file.
+knwhosts="$sshdir"/known_hosts # Path to known_hosts file.
  confile=~/.sshtorc            # Path to config file, have to be chmod'ed to 600.
  tmpfile=/tmp/sshtorc-${USER}  # Path to tmp file to save selected context.
 sshto_script[0]=~              # Path to sshto script
@@ -244,8 +244,38 @@ system_info(){
 #------------------------{ Show\Edit ssh config }-----------------------------------------------------------------------
 show_conf(){ clear; ssh -G $target; pause; }
 edit_conf(){
-    local   confs   search=$target
+    local new_group search=$target new_filename group_list name confs data
     [[ $group ]] && search="$group_id[[:space:]]*#$group#"
+    [[ $group == 'Selected_hosts' ]] && {
+        dialog --yesno 'Save this group as permanent config file?' 5 45 || return
+        new_group=$(D "RUN" '' "BACK" '' --inputbox "Set new group(file) name:" 8 80 "$new_group")
+        case $new_group:$? in
+                     '':0) return;;
+                      *:0) new_filename=~/.ssh/config_"${new_group// /_}"
+                           new_filename=${new_filename,,}
+                           [[ -f $new_filename ]] && {
+                                dialog --defaultno --yesno 'File exists, overwrite?' 5 45 || return
+                           }
+                           data="#Host DUMMY #$new_group#"
+                           group_list=("${selected_list[@]:2}")
+                           for ((i=0;  i<${#group_list[@]}; i+=2)); do
+                                name="${group_list[$i]}"
+                                data+="$(
+                                    echo; echo
+                                    gawk -vname="$name" '
+                                        BEGIN{IGNORECASE=1}
+                                        {
+                                            if ($1 == "host" && $2 == name){start=1}
+                                            if (start){if ($0 ~ /^#|^$/){exit}; print }
+                                        }
+                                    '   $CONFILES
+                                )"
+                           done
+                           echo "$data" > "$new_filename"
+                           return;;
+                      *:*) return;;
+        esac
+    }
     confs=($(grep -rilE "Host[[:space:]]*$search" $CONFILES)) || { clear; echo 'Config file not found'; pause; return; }
     $EDITOR "${confs[@]}"
 }
@@ -469,19 +499,22 @@ new_list(){
 
 contents_menu(){
     local filter_tmp=$filter selected=
-    [[  ${selected_list[@]} ]] && selected='Selected_hosts'
+    [[ ${selected_list[@]} ]] && selected='Selected_hosts'
 
-    local btns=('SELECT' 'RUN COMMAND' 'BACK' '')
+    local btns=('SELECT' 'RUN COMMAND' 'RELOAD' 'BACK')
 	filter=$(D "${btns[@]}" --no-items --menu "Select list of hosts:" 0 0 0 "All" $selected "${content[@]}")
 	case $filter:$? in
              All:0) list=( "${selected_list[@]}" "${fullist[@]}" )
                     save_tmp       "filter=";;
                *:3) second_dialog "$filter" ;;
-               *:1) filter=$filter_tmp;;
+               *:2) filter=$filter_tmp;;
+               *:1) restart; contents_menu;;
                *:0) new_list;;
 	esac        ;   first_dialog
 }
-
+# Dialog buttons order and exit codes
+#<OK> <Extra> <Cancel> <Help>
+# 0      3       1       2
 #------------------------{ Selector }-----------------------------------------------------------------------------------
 declare -A slctd_hosts
 declare -A slctd_groups
@@ -590,49 +623,54 @@ second_dialog(){
 
 #-------------{ Create the list of hosts. Get hosts and descriptions from ~/.ssh/config* }------------------------------
 desclength=20
-declare    -A      hostnames
-while read -r name hostname desc; do
-    case    ${name,,} in
-        'group_name') name="{ $desc }"
-                      name_length=${#name}
-                      name_left=$[(40-name_length)/2]
-                      name_right=$[40-(name_left+name_length)]
-                      printf -v tmp "%${name_left}s_NAME_%${name_right}s"
-                      tmp=${tmp// /-}  name=${tmp//_NAME_/$name}
-                      content+=( "$desc" );  desc='_LINE_';;
-                '#'*) continue;;
-    esac
-    ((${#desc}>desclength)) && desclength=${#desc}
-    hostnames["$name"]=$hostname #Create host-hostname pairs in hostnames array
-    fullist+=("$name" "$desc")   #Add Host and Description to the list
-done < <(gawk '
-BEGIN{IGNORECASE=1}
-/Host /{
-    strt=1
-    host=$2
-    desc=gensub(/^.*Host .* #(.*)/, "\\1", "g", $0)
-    desc=gensub(/(.*)#.*/,          "\\1", "g", desc)
-    next
-}
-strt && host == "'"$group_id"'"{
-    print "group_name", "dummy", desc
-    strt=0
-}
-strt && /HostName /{
-    hostname=$2
-    print host, hostname, desc
-    strt=0
-}'  $CONFILES)
+restart(){
+    fullist=()
+    content=()
+    selected_list=()
+    declare -A hostnames=()
+    CONFILES=$(shopt -s nullglob; echo "$sshdir"/{config,config*[!~]}) # SSH confiles list.
+    while read -r name hostname desc; do
+        case    ${name,,} in
+            'group_name') name="{ $desc }"
+                          name_length=${#name}
+                          name_left=$[(40-name_length)/2]
+                          name_right=$[40-(name_left+name_length)]
+                          printf -v tmp "%${name_left}s_NAME_%${name_right}s"
+                          tmp=${tmp// /-}  name=${tmp//_NAME_/$name}
+                          content+=( "$desc" );  desc='_LINE_';;
+                    '#'*) continue;;
+        esac
+        ((${#desc}>desclength)) && desclength=${#desc}
+        hostnames["$name"]=$hostname #Create host:hostname pairs in hostnames array
+        fullist+=("$name" "$desc")   #Add Host and Description to the list
+    done < <(gawk '
+    BEGIN{IGNORECASE=1}
+    /Host /{
+        strt=1
+        host=$2
+        desc=gensub(/^.*Host .* #(.*)/, "\\1", "g", $0)
+        desc=gensub(/(.*)#.*/,          "\\1", "g", desc)
+        next
+    }
+    strt && host == "'"$group_id"'"{
+        print "group_name", "dummy", desc
+        strt=0
+    }
+    strt && /HostName /{
+        hostname=$2
+        print host, hostname, desc
+        strt=0
+    }'  $CONFILES)
 
-descline=$(line - $desclength)
-list=( "${fullist[@]}" )
-N=${#fullist[@]}
-
-[[ -e $tmpfile ]] && . "$tmpfile"
-[[    $filter  ]] &&    new_list
+    descline=$(line - $desclength)
+    list=( "${fullist[@]}" )
+    N=${#fullist[@]}
+}
 
 #--{ Go baby, GO!) }--
-check_confile
+check_confile;  restart
+[[ -e $tmpfile  ]] && . "$tmpfile"
+[[    $filter   ]] &&    new_list
 [[ $target      ]] || first_dialog
 [[ $OPT =~ name ]] && { echo $target; exit; }
 [[ $target      ]] && second_dialog
