version 1.02 Support Include directive of ssh configs. List of hosts groups is sorted by name. Few touches here and there.

diff --git a/sshto b/sshto
--- a/sshto
+++ b/sshto
@@ -21,7 +21,7 @@ sshto_script[0]=~              # Path to sshto script
 sshto_script[1]=.sshto_script  # Sshto script filename
 sshto_script[2]="${sshto_script[0]}/${sshto_script[1]}" # Sshto script full
 #------------------------{ Help and version }---------------------------------------------------------------------------
-version=1.01
+version=1.02
 help="sshto - SSH connection manager, powered by Dialog
 
 Usage:
@@ -293,7 +293,7 @@ edit_conf(){
                                             if ($1 == "host" && $2 == name){start=1}
                                             if (start){if ($0 ~ /^#|^$/){exit}; print }
                                         }
-                                    '   $CONFILES
+                                    '   "${confiles[@]}"
                                 )"
                            done
                            echo "$data" > "$new_filename"
@@ -301,7 +301,7 @@ edit_conf(){
                       *:*) return;;
         esac
     }
-    confs=($(grep -rilE "Host[[:space:]]*$search" $CONFILES)) || { clear; echo 'Config file not found'; pause; return; }
+    confs=($(grep -RilE "Host[[:space:]]*$search" "${confiles[@]}")) || { clear; echo 'Config file not found'; pause; return; }
     $EDITOR "${confs[@]}"
 }
 
@@ -682,19 +682,27 @@ second_dialog(){
 	esac         ;   second_dialog "$group"
 }
 
+
 #-------------{ Create the list of hosts. Get hosts and descriptions from ~/.ssh/config* }------------------------------
 declare -A hostnames=()
 desclength=20
 restart(){
     fullist=()
     content=()
+    confiles=()
     hostnames=()
     selected_list=()
-    CONFILES=$( # SSH confiles list.
-        shopt -s nullglob
-        echo  "$sshdir"/config*[!~]
-        [[ -f "$sshdir"/config ]] && echo "$sshdir"/config
-    )
+    the_config="$sshdir/config"
+    confiles+=("$the_config")
+    confiles+=($( # check for includes in config files
+        grep -REhi '^[[:space:]]*include[[:space:]]+[^[:space:]]*' "$sshdir/" | \
+        gawk -vconf="$sshdir" 'BEGIN{IGNORECASE=1}{
+            pattern=gensub("^[[:space:]]*include[[:space:]]+([^[:space:]]*.*)$","\\1","g",$0)
+            pattern=gensub(/\042|\047/,"","g",pattern)
+            cmd="find \"" conf "\" -type f -name \"" pattern "\""
+            system(cmd)
+        }'
+    ))
 
     while read -r name hostname desc; do
         case    ${name,,} in
@@ -710,7 +718,7 @@ restart(){
         ((${#desc}>desclength)) && desclength=${#desc}
         hostnames["$name"]=$hostname #Create host:hostname pairs in hostnames array
         fullist+=("$name" "$desc")   #Add Host and Description to the list
-    done < <(gawk '
+    done < <(gawk -vgroup_id="$group_id" '
     BEGIN{IGNORECASE=1}
     /Host /{
         strt=1
@@ -732,7 +740,7 @@ restart(){
         }
         next
     }
-    strt && host == "'"$group_id"'"{
+    strt && host == group_id {
         print "group_name", "dummy", desc
         strt=0
     }
@@ -743,7 +751,7 @@ restart(){
         }
         strt=0
         delete hosts
-    }'  $CONFILES)
+    }'  "${confiles[@]}")
 
     descline=$(line - $desclength)
     list=( "${fullist[@]}" "${quick_butt[@]}" )
@@ -755,6 +763,13 @@ restart(){
         "$qcmd"   "$descline"
         "$qbut1"  "Create list of hosts filtered by pattern"
     )
+
+    # sort the content
+    sorted_content=()
+    while read line; do
+        sorted_content+=("$line")
+    done < <(printf '%s\n' "${content[@]}" | sort)
+    content=("${sorted_content[@]}")
 }
 
 #--{ Go baby, GO!) }--
